version: '3.8'

services:
  # Aplicación principal
  app:
    build: .
    container_name: products-app
    ports:
      - "8081:8080"
    environment:
      - INSTANCE_ID=main-app
      - DB_HOST=db
      - REDIS_HOST=cache
    depends_on:
      - cache
      - db
    networks:
      - app-network

  # Cache compartido (Valkey - fork open-source de Redis)
  cache:
    image: valkey/valkey:7
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Base de datos compartida
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: productsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
