version: '3.8'

services:
  cache:
    image: redis:7
    container_name: cache
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: productsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
